# Generated by Django 4.2 on 2023-07-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Panel', '0003_alter_food_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='tablebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=300)),
                ('contact', models.BigIntegerField()),
                ('person', models.BigIntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
