# Generated by Django 4.2 on 2023-07-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Panel', '0004_tablebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=25)),
                ('comment', models.CharField(max_length=300)),
                ('photo', models.FileField(default='', upload_to='')),
            ],
        ),
    ]
