# Generated by Django 4.2 on 2023-10-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Panel', '0005_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
