# Generated by Django 4.2.5 on 2023-10-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Panel', '0006_alter_food_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin_slider',
        ),
    ]
